# Generated by Django 4.0.6 on 2022-07-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='abi',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='cab',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='cap2',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='cellurare',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='citta2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='fa',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='indirizzo2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='nome2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='note',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='pec',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='provincia2',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
