# Generated by Django 4.0.6 on 2022-08-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0003_alter_anagrafica_cellurare_alter_anagrafica_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='cellurare',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
