# Generated by Django 4.0.6 on 2022-08-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0004_alter_anagrafica_cellurare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
